bb<-read.table("~/analysis/data/hapblock/BB_allhb.blocks.det",header=TRUE)
vb<-read.table("~/analysis/data/hapblock/VB_allhb.blocks.det",header=TRUE)
pb<-read.table("~/analysis/data/hapblock/PB_allhb.blocks.det",header=TRUE)
sj<-read.table("~/analysis/data/hapblock/SJ_allhb.blocks.det",header=TRUE)
bnp<-read.table("~/analysis/data/hapblock/BNP_allhb.blocks.det",header=TRUE)
sp<-read.table("~/analysis/data/hapblock/SP_allhb.blocks.det",header=TRUE)
gb<-read.table("~/analysis/data/hapblock/GB_allhb.blocks.det",header=TRUE)

bbt<-density(bb[,4],na.rm=TRUE)
vbt<-density(vb[,4],na.rm=TRUE)
pbt<-density(pb[,4],na.rm=TRUE)
sjt<-density(sj[,4],na.rm=TRUE)
bnpt<-density(bnp[,4],na.rm=TRUE)
spt<-density(sp[,4],na.rm=TRUE)
gbt<-density(gb[,4],na.rm=TRUE)

par(mfrow=c(1,1),mar=c(4,5,2,2))
plot(bbt,xlim=c(0,5),col="black",bty="l",ylim=c(0,40),cex.lab=2,cex.lab=2,xlab="Haplotype block size [kb]")
lines(vbt,xlim=c(0,.025),col="grey")
lines(pbt,xlim=c(0,.025),col="red")
lines(sjt,xlim=c(0,.025),col="darkorange")
lines(bnpt,xlim=c(0,.025),col="gold")
lines(spt,xlim=c(0,.025),col="cyan")
lines(gbt,xlim=c(0,.025),col="blue")
polygon(bbt,col="black",density=100)
polygon(vbt,col="grey",density=100)
polygon(pbt,col="red",density=100)
polygon(sjt,col="darkorange",density=100)
polygon(bnpt,col="gold",density=100)
polygon(spt,col="cyan",density=100)
polygon(gbt,col="blue",density=100)
